name: tsl
version: 1.3.1.0
synopsis: Library and tools for the TSL specification format
description: Library and tools for the TSL specification format
license: OtherLicense
license-file: LICENSE
author:
  - Felix Klein <felix.klein@cispa.de>
  - Mark Santolucito <mark.santolucito@yale.edu>
  - Philippe Heim <philippe.heim@cispa.de>
  - Gideon Geier <gideon.geier@cispa.de>
  - Marvin Stenger <marvin.stenger@cispa.de>
  - Wonhyuk Choi <wonhyuk.choi@columbia.edu>
  - Feitong Leo Qiao <leo.qiao@columbia.edu>
category: Synthesis
build-type: Simple

language: Haskell2010

extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  # - -fno-ignore-asserts

dependencies:
  - base >= 4.13 && <4.19

library:
  source-dirs: src/lib
  ghc-options:
    - -Wall
    - -Wno-name-shadowing
    - -fno-ignore-asserts
  dependencies:
    - directory >= 1.3
    - filepath >= 1.4
    - parsec >=3.1 && <3.2
    - array >=0.5 && <0.6
    - mtl >=2.2 && <2.3
    - containers >=0.5 && <0.7
    - QuickCheck
    - process >= 1.6.3.0
    - ansi-terminal >= 0.6
    - transformers >= 0.5.6.2
    - process
    - fgl >= 5.6.0.0
    - hanoi
    - finite
    - text
    - pcre-heavy

executables:
  tsl:
    main: Main.hs
    source-dirs:
      - src/tools/tsl
    dependencies:
      - tsl
      - optparse-applicative

tests:
  default:
    main: Test.hs
    source-dirs: src/test
    dependencies:
      - tsl
      - containers >=0.5 && <0.7
      - QuickCheck
      - Cabal >=2.4
      - filepath >= 1.4
      - directory >= 1.3
      - ansi-terminal >= 0.6
      - transformers >= 0.5.6.2
      - process
      - hanoi
      - process
      - HUnit 