on: [push]
name: build
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v7
  build:
    name: Hello World
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    needs: ormolu
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: make
      - run: stack test
