on: [push]
name: build
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/run-ormolu@v11
  build:
    name: TSL test suite
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    needs: ormolu
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: mkdir deps
      - run: wget https://github.com/cvc5/cvc5/releases/latest/download/cvc5-Linux
      - run: mv cvc5-Linux deps/cvc5
      - run: chmod u+x deps/cvc5
      - run: stack test
