on: [push]
name: build
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/run-ormolu@v11
  build:
    name: TSL test suite
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    needs: ormolu
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: mkdir deps-bin deps-src
      - run: wget -P deps-src https://github.com/cvc5/cvc5/releases/download/cvc5-1.1.1/cvc5-Linux-static.zip
      - run: unzip deps-src/cvc5-Linux-static.zip -d deps-src
      - run: mv deps-src/cvc5-Linux-static/bin/cvc5 deps-bin
      - run: chmod u+x deps-bin/cvc5
      - run: PATH="deps-bin:$PATH" stack test
